import type { Dealer } from "@brand/shared/types/dealers";
import { SERVICE_CENTERS } from "./service-centers";

const SERVICE_DEALERS: Dealer[] = SERVICE_CENTERS.map((sc) => ({
  id: sc.id,
  name: sc.name,
  address: sc.address,
  phone: sc.phone,
  email: sc.email,
  category: "service",
  coordinates: sc.coords,
}));

// Array order IS display order: /gde-kupiti lists it as-is, and product pages show
// only the first 6 non-service entries (product-detail-page.tsx filters, then
// product-detail.tsx slices). Ours first, then online shops by reach, then dealers.
export const DEALERS: Dealer[] = [
  {
    id: "prodavnica-alata",
    name: "Prodavnica Alata",
    address: "Vojislava Ilića 141g",
    city: "Beograd",
    phone: "011/4520-171",
    email: "office@prodavnicaalata.rs",
    website: "https://www.prodavnicaalata.rs/",
    logoSrc: "/companies/svgs/prodavnicaalata.svg",
    category: "online",
    coordinates: { lat: 44.785937879592375, lng: 20.500689934951087 },
  },
  {
    // Carries DCK at /proizvodjaci/dck-alati/
    id: "od-igle-do-lokomotive",
    name: "Od Igle Do Lokomotive",
    address: "Radoja Dakića 18",
    city: "Niš",
    phone: "018/575-773",
    email: "office@odigledolokomotive.rs",
    website: "https://www.odigledolokomotive.rs/",
    logoSrc: "/companies/svgs/odigledolokomotive.webp",
    category: "online",
    coordinates: { lat: 43.3200296, lng: 21.9270237 },
  },
  {
    // Carries DCK at /dck
    id: "kliklak",
    name: "Kliklak",
    address: "Matejevački put 36",
    city: "Niš",
    phone: "018/3230-264",
    email: "info@kliklak.rs",
    website: "https://www.kliklak.rs/",
    logoSrc: "/companies/svgs/kliklak.webp",
    category: "online",
    coordinates: { lat: 43.331145, lng: 21.937353 },
  },
  {
    id: "sualati-024",
    name: "Sualati 024",
    address: "Segedinski put 86",
    city: "Subotica",
    phone: "024/525-091",
    email: "sualati@gmail.com",
    website: "https://www.sualati.com/",
    logoSrc: "/companies/svgs/sualati.png",
    category: "online",
    coordinates: { lat: 46.099807, lng: 19.6966443 },
  },
  {
    // "G-SCENT" D.O.O. (PIB 108666525) - webshop only, no retail location
    id: "alati-i-oprema",
    name: "Alati i Oprema",
    address: "Jurija Gagarina 68",
    city: "Novi Beograd",
    phone: "061/243-4739",
    email: "info@alati-i-oprema.rs",
    website: "https://alati-i-oprema.rs/",
    category: "online",
    coordinates: { lat: 44.8036781, lng: 20.3803287 },
  },
  {
    id: "stridon-group",
    name: "Stridon Group D.O.O.",
    address: "Vojislava Ilića 141g",
    city: "Beograd",
    phone: "011/4520-171",
    email: "office@stridon.rs",
    website: "https://www.stridon.rs/",
    logoSrc: "/companies/svgs/stridon.webp",
    category: "dealer",
    coordinates: { lat: 44.785937879592375, lng: 20.500689934951087 },
  },
  {
    id: "tim-komerc",
    name: "Tim Komerc",
    address: "Paunova 8",
    city: "Beograd",
    phone: "011/3984-584",
    email: "tim.1@mts.rs",
    website: "https://www.timkomerc.rs/",
    category: "dealer",
    coordinates: { lat: 44.759211, lng: 20.475917 },
  },
  {
    id: "triar",
    name: "Triar",
    address: "Zemunska 267A",
    city: "Ugrinovci",
    phone: "063/865-2542",
    email: "triar267@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.896542, lng: 20.246676 },
  },
  {
    id: "srnic-alati",
    name: "Srnić Alati",
    address: "Kralja Milutina 112",
    city: "Šabac",
    phone: "062/166-6202",
    email: "markosrnic@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.743224, lng: 19.696605 },
  },
  {
    id: "alati-dms",
    name: "Alati DMS",
    address: "Profesora Andonovića 16",
    city: "Ralja",
    phone: "063/171-5805",
    email: "sasa.lazic0@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.57595, lng: 20.559898 },
  },
  {
    id: "gvozdara-021-plus",
    name: "Gvožđara 021 Plus",
    address: "Laze Lazarevića 18",
    city: "Novi Sad",
    phone: "063/199-5370",
    email: "vland833@gmail.com",
    category: "dealer",
    coordinates: { lat: 45.2371038, lng: 19.8219239 },
  },
  {
    id: "goks",
    name: "Goks",
    address: "Put za Ovču 15A",
    city: "Borča",
    phone: "011/3327-449",
    email: "goksboje@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.8802963, lng: 20.4679465 },
  },
  {
    id: "mb-alati-i-oprema",
    name: "MB Alati i Oprema",
    address: "Cara Dušana 73",
    city: "Pančevo",
    phone: "062/626-341",
    email: "mbalatiioprema@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.8643703, lng: 20.6533224 },
  },
  {
    id: "dmp-cosmos-electric",
    name: "DMP Cosmos Electric",
    address: "Kneza Mihajla 1A",
    city: "Paraćin",
    phone: "063/649-999",
    email: "dmp.cosmos.electric@gmail.com",
    category: "dealer",
    coordinates: { lat: 43.857138, lng: 21.413128 },
  },
  {
    id: "stolarski-centar",
    name: "Stolarski Centar Vera Krstić",
    address: "Ribarska obala 10",
    city: "Sremska Mitrovica",
    phone: "022/624-761",
    email: "stolarskicentar@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.9707916, lng: 19.6011929 },
  },
  {
    id: "uradimo-sami",
    name: "Uradimo Sami",
    address: "Kneza Višeslava 31u",
    city: "Beograd",
    phone: "011/2473-913",
    email: "uradimosami@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.7593747, lng: 20.4365874 },
  },
  {
    id: "izbor-kovin",
    name: "Izbor Kovin",
    address: "Cara Lazara 128",
    city: "Kovin",
    phone: "013/742-950",
    email: "dooizbor@gmail.com",
    category: "dealer",
    coordinates: { lat: 44.7445793, lng: 20.9796815 },
  },
  {
    id: "fish-and-food",
    name: "Fish & Food",
    address: "Glavna 65",
    city: "Bečej",
    phone: "062/207-952",
    email: "veleprodajatisaplus@gmail.com",
    category: "dealer",
    coordinates: { lat: 45.6198748, lng: 20.0406751 },
  },
  {
    id: "zim-commerce",
    name: "Zim Commerce",
    address: "Majšanski put 128",
    city: "Subotica",
    phone: "024/577-566",
    email: "zimcommercedoo@gmail.com",
    website: "https://zimcommerce.com/",
    category: "dealer",
    coordinates: { lat: 46.1211133, lng: 19.674982 },
  },
  {
    id: "elektro-025",
    name: "Elektro 025",
    address: "Dimitrija Tucovića 105",
    city: "Apatin",
    phone: "069/250-4456",
    email: "elektro025apatin@gmail.com",
    website: "https://www.elektro025.com/",
    category: "dealer",
    coordinates: { lat: 45.67155, lng: 18.986675 },
  },
  ...SERVICE_DEALERS,
];
